version: '3'

services:
  nginx:
    image: nginx:12.5-alpine
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"

  tomcat:
    depends_on:
      postgres:
        condition: service_healthy
    image: tomcat:10.1.19-jre21
    hostname: tomcat
    networks:
      - ssbd01
    ports:
      - "8080:8080"
    container_name: tomcat
    volumes:
      - '../target/EventSymphony.war:/usr/local/tomcat/webapps/EventSymphony.war:ro'

  postgres:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pg:

networks:
  ssbd01:
    driver: bridge

