version: '3'

services:
  nginx:
    image: ssbd01/nginx:v0.11
    volumes:
      -  /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"

  tomcat:
    image: tomcat:10.1.19-jre21
    ports:
      - "8080:8080"

  postgres:
    image: postgres:16.2
    restart: always
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:

