version: '3'

services:
  nginx:
    depends_on:
      - tomcat
    image: nginx:1.25.4
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    build:
        context: .
        dockerfile: Dockerfile
    hostname: nginx
    container_name: nginx
    networks:
          - ssbd01
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  tomcat:
    depends_on:
      postgres:
        condition: service_healthy
    image: tomcat:10.1.19-jre21
    environment:
      DEEPL_KEY: ${DEEPL_KEY}
    hostname: tomcat
    container_name: tomcat
    networks:
      - ssbd01
    ports:
      - "8080:8080"
    volumes:
      - '../target/ssbd01.war:/usr/local/tomcat/webapps/ssbd01.war'

  postgres:
    image: postgres:16.2
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ssbd01admin" ]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: postgres
    container_name: postgres
    networks:
      - ssbd01
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data
      - ./create-users.sql:/docker-entrypoint-initdb.d/create-users.sql

volumes:
  pg:

networks:
  ssbd01:
    driver: bridge

