version: '3'

services:
  tomcat:
    depends_on:
      postgres:
        condition: service_healthy
    image: tomcat:10.1.19-jre21
    hostname: tomcat
    container_name: tomcat_test
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
    networks:
      - ssbd01_test
    ports:
      - "28080:8080"
    volumes:
      - '../target/ssbd01.war:/usr/local/tomcat/webapps/ssbd01.war'

  postgres:
    image: postgres:16.2
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ssbd01admin" ]
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: postgres
    container_name: postgres_test
    networks:
      - ssbd01_test
    ports:
      - "54320:5432"
    volumes:
      - pg_test:/var/lib/postgresql/data
      - ./create-users.sql:/docker-entrypoint-initdb.d/create-users.sql

volumes:
  pg_test:

networks:
  ssbd01_test:
    driver: bridge

